# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- azure-pipelines

pool:
  vmImage: 'macos-latest'

steps:
- script: |
        df -h
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install autoconf expect
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        clang --version
        ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
        cd /Users/runner
        ls
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 200g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
  displayName: ' Initialization environment'

- script: |
    df -h
    git config --global user.name "ittat"
    git config --global user.email "ittat@github.com"
    cd /Volumes/android
    git clone https://github.com/ReB2GOS/B2G -b master
    cd ./B2G
    REPO_INIT_FLAGS="--depth=1" REPO_SYNC_FLAGS="-j128" ./config.sh emulator-10
  displayName: 'Fetch source'

- script: |
    df -h
    cd /Volumes/android
    ls
    cd ./B2G/gecko
    touch ./boot.exp
    echo "spawn ./mach bootstrap --no-system-changes" >> boot.exp  
    echo "expect  \"Your choice:\" " >> boot.exp
    echo "send \"4\r\" " >> boot.exp
    echo "expect  \"(Yn):\" " >> boot.exp
    echo "send \"Y\r\" " >> boot.exp
    echo "expect  \"(Yn):\" " >> boot.exp
    echo "send \"Y\r\" " >> boot.exp

    echo "interact " >> boot.exp
    cat ./boot.exp
    expect ./boot.exp
    cd ../
    sed -i '' '65i\'$'\n\"10\.15\"\,' build/soong/cc/config/x86_darwin_host.go
    cat ./build/soong/cc/config/x86_darwin_host.go
    export LOCAL_NDK_BASE_URL='ftp://ftp.kaiostech.com/ndk/android-ndk'
    ./build.sh -j16
    hdiutil detach /Volumes/android
  displayName: 'build source'

