# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- azure-pipelines
jobs:
- job: build
  pool:
    vmImage: 'macOS-10.15'
  timeoutInMinutes: 360
  steps:
  - script: |
        df -h
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install autoconf expect
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 100g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        df -h
        sudo xcode-select --switch /Applications/Xcode_10.3.app/Contents/Developer
        sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
        brew reinstall python@3
    displayName: ' Initialization environment'

  - script: |
        df -h
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        cd /Volumes/android
        mkdir ~/bin
        export PATH=~/bin:$PATH
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        repo init -u https://github.com/ReB2GOS/manifests -b ndk --depth=1
        repo sync -j128 --no-tags --no-clone-bundle
        df -h
    displayName: 'Fetch source'



  - script: |
        df -h
        cd /Volumes/android
        /usr/local/bin/python2.7 ndk/checkbuild.py --no-build-tests
        df -h
    displayName: 'build ndk'



