# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    df -h
    dpkg-query -Wf '${Installed-size}\t${Status}\t${Package}\n'|grep deinstall|awk '{print $5}'|xargs dpkg -P
  displayName: ' Initialization environment'

- script: |
    sudo apt-get update
    sudo apt-get install -y  --no-install-recommends  git 
    sudo rm -rf \
      /usr/share/dotnet \
      /etc/mysql \
      /etc/php
    git config --global user.name "ittat"
    git config --global user.email "ittat@github.com"
    df -h
  displayName: 'Run a multi-line script'
