# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- azure-pipelines
jobs:
- job: build
  pool:
    vmImage: 'macOS-10.14'
  timeoutInMinutes: 360
  steps:
  - script: |
        df -h
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install ccache
        more /System/Library/CoreServices/SystemVersion.plist
        sudo xcode-select --switch /Applications/Xcode_10.3.app/Contents/Developer
        #ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        #ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 100g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        df -h
        sudo ls /Applications
        sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer
        sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
        sudo ls /System/Library/Frameworks/Python.framework/Versions/
        #sudo cp ./build/lib.macosx-10.4-x86_64-2.6/_scproxy.so /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload
    displayName: ' Initialization environment'

  - script: |
        df -h
        export CCACHE_DIR=~/.ccache
        /usr/local/bin/ccache  -M 70G
        /usr/local/bin/ccache -s
        export USE_CCACHE=1
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        cd /Volumes/android
        mkdir ~/bin
        export PATH=~/bin:$PATH
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        #repo init -u https://github.com/ReB2GOS/manifests -b ndk --depth=1
        repo init -u https://android.googlesource.com/platform/manifest -b master-ndk  --depth=1
        repo sync  -j128 --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune
        df -h
    displayName: 'Fetch source'



  - script: |
        df -h
        cd /Volumes/android
        #python ndk/checkbuild.py --no-build-tests
        ls
        python checkbuild.py
        df -h
    displayName: 'build ndk'



