# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- azure-pipelines


# variables:
#   # DEBUG
#     system.debug: true

jobs:

- job: build

  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 360


  steps:

  - script: |
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        mkdir ~/android
        cd ~/android
        git clone  https://github.com/ReB2GOS/gecko-b2g -b test4 --depth=1
        #git clone https://github.com/mozilla/gecko-dev -b master --depth=1
    displayName: ' Initialization environment'




  - script: |
      # Install tmate on macOS or Ubuntu
      echo Setting up tmate...
      if [ -x "$(command -v brew)" ]; then
        brew install tmate > /tmp/brew.log
      fi
      if [ -x "$(command -v apt-get)" ]; then
        curl -fsSL git.io/tmate.sh | bash
      fi
      [ -e ~/.ssh/id_rsa ] || ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
      echo Running tmate...
      tmate -S /tmp/tmate.sock new-session -d
      tmate -S /tmp/tmate.sock wait tmate-ready
      # Print connection info
      DISPLAY=1
      while [ $DISPLAY -le 3 ]; do
        echo ________________________________________________________________________________
        echo To connect to this session copy-n-paste the following into a terminal or browser:
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
        [ ! -f /tmp/keepalive ] && echo -e "After connecting you can run 'touch /tmp/keepalive' to disable the 30m timeout"
        DISPLAY=$(($DISPLAY+1))
        sleep 30
      done
      if [[ ! -z "$SLACK_WEBHOOK_URL" ]]; then
        MSG=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"\`$MSG\`\"}" $SLACK_WEBHOOK_URL
      fi
      # Wait for connection to close or timeout in 15 min
      timeout=$((30*60))
      while [ -S /tmp/tmate.sock ]; do
        sleep 1
        timeout=$(($timeout-1))
        if [ ! -f /tmp/keepalive ]; then
          if (( timeout < 0 )); then
            echo Waiting on tmate connection timed out!
            sudo init 0
            exit 0
          fi
        fi
      done
    displayName:  tmate



