# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- azure-pipelines
jobs:
- job: build
  pool:
    vmImage: 'macOS-10.14'
  timeoutInMinutes: 360
  steps:
  - script: |
        df -h
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install ccache
        more /System/Library/CoreServices/SystemVersion.plist
        sudo xcode-select --switch /Applications/Xcode_10.3.app/Contents/Developer
        #ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        #ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 100g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        df -h
        sudo ls /Applications
        sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer
        sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
        sudo ls /System/Library/Frameworks/Python.framework/Versions/
        #sudo cp ./build/lib.macosx-10.4-x86_64-2.6/_scproxy.so /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload
    displayName: ' Initialization environment'

  - script: |
        df -h
        export CCACHE_DIR=~/.ccache
        /usr/local/bin/ccache  -M 70G
        /usr/local/bin/ccache -s
        export USE_CCACHE=1
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        cd /Volumes/android
        mkdir ~/bin
        export PATH=~/bin:$PATH
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        repo init -u https://github.com/ReB2GOS/manifests -b ndk --depth=1
        #repo init -u https://android.googlesource.com/platform/manifest -b ndk-release-r20  --depth=1
        repo sync  -j128 --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune
        df -h
    displayName: 'Fetch source'



  - script: |
        df -h
        cd /Volumes/android
        python ndk/checkbuild.py --no-build-tests
        ls
        #python checkbuild.py
        df -h
    displayName: 'build ndk'



  # - script: |
  #     # Install tmate on macOS or Ubuntu

  #     echo Setting up tmate...
  #     if [ -x "$(command -v brew)" ]; then
  #       brew install tmate > /tmp/brew.log
  #     fi

  #     if [ -x "$(command -v apt-get)" ]; then
  #       curl -fsSL git.io/tmate.sh | bash
  #     fi
  #     [ -e ~/.ssh/id_rsa ] || ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
  #     echo Running tmate...
  #     tmate -S /tmp/tmate.sock new-session -d
  #     tmate -S /tmp/tmate.sock wait tmate-ready

  #     # Print connection info
  #     DISPLAY=1
  #     while [ $DISPLAY -le 3 ]; do
  #       echo ________________________________________________________________________________
  #       echo To connect to this session copy-n-paste the following into a terminal or browser:
  #       tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
  #       tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
  #       [ ! -f /tmp/keepalive ] && echo -e "After connecting you can run 'touch /tmp/keepalive' to disable the 30m timeout"
  #       DISPLAY=$(($DISPLAY+1))
  #       sleep 30
  #     done

  #     if [[ ! -z "$SLACK_WEBHOOK_URL" ]]; then
  #       MSG=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
  #       curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"\`$MSG\`\"}" $SLACK_WEBHOOK_URL
  #     fi

  #     # Wait for connection to close or timeout in 15 min
  #     timeout=$((30*60))
  #     while [ -S /tmp/tmate.sock ]; do
  #       sleep 1
  #       timeout=$(($timeout-1))

  #       if [ ! -f /tmp/keepalive ]; then
  #         if (( timeout < 0 )); then
  #           echo Waiting on tmate connection timed out!
  #           sudo init 0
  #           exit 0
  #         fi
  #       fi
  #     done
  #   displayName:  tmate


