# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'macos-latest'

steps:
- script: |
        df -h
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install autoconf
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
  displayName: ' Initialization environment'

- script: |
    df -h
    pwd
    git config --global user.name "ittat"
    git config --global user.email "ittat@github.com"
    git clone https://github.com/ReB2GOS/B2G -b exp
    cd ./B2G
    REPO_INIT_FLAGS="--depth=1" REPO_SYNC_FLAGS="-j128" ./config.sh emulator-10
  displayName: 'Fetch source'

- script: |
    df -h
    cd /Users/runner/runners/2.165.2/work/1/s/B2G
    ls
    export LOCAL_NDK_BASE_URL='ftp://ftp.kaiostech.com/ndk/android-ndk'
    cd gecko && ./mach bootstrap && 4
    cd ../
    ./build.sh -j16
  displayName: 'build source'

