#!/bin/bash

export GONK_PATH=`pwd`
export GECKO_PATH=${GONK_PATH}/gecko

# Package the sysroot
SYSROOT_PREBUILTS="prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/lib/gcc/x86_64-linux-android/4.9.x"

SYSROOT_LIBRARIES="out/target/product/onyx/system/lib/android.hardware.gnss@1.0.so
out/target/product/onyx/system/lib/android.hardware.gnss@1.1.so
out/target/product/onyx/system/lib/android.hardware.gnss@2.0.so
out/target/product/onyx/system/lib/android.hardware.radio@1.0.so
out/target/product/onyx/system/lib/android.hardware.gnss.visibility_control@1.0.so
out/target/product/onyx/system/lib/android.hardware.sensors@1.0.so
out/target/product/onyx/system/lib/android.hardware.vibrator@1.0.so
out/target/product/onyx/system/lib/android.hardware.wifi@1.0.so
out/target/product/onyx/system/lib/android.hardware.wifi@1.1.so
out/target/product/onyx/system/lib/android.hardware.wifi@1.2.so
out/target/product/onyx/system/lib/android.hardware.wifi@1.3.so
out/target/product/onyx/system/lib/android.hardware.wifi.hostapd@1.0.so
out/target/product/onyx/system/lib/android.hardware.wifi.hostapd@1.1.so
out/target/product/onyx/system/lib/android.hardware.wifi.supplicant@1.0.so
out/target/product/onyx/system/lib/android.hardware.wifi.supplicant@1.1.so
out/target/product/onyx/system/lib/android.hardware.wifi.supplicant@1.2.so
out/target/product/onyx/system/lib/binder_b2g_connectivity_interface-cpp.so
out/target/product/onyx/system/lib/binder_b2g_telephony_interface-cpp.so
out/target/product/onyx/system/lib/dnsresolver_aidl_interface-V2-cpp.so
out/target/product/onyx/system/lib/libaudioclient.so
out/target/product/onyx/system/lib/libbase.so
out/target/product/onyx/system/lib/libbinder.so
out/target/product/onyx/system/lib/libcamera_client.so
out/target/product/onyx/system/lib/libc++.so
out/target/product/onyx/system/lib/libcutils.so
out/target/product/onyx/system/lib/libgui.so
out/target/product/onyx/system/lib/libhardware_legacy.so
out/target/product/onyx/system/lib/libhardware.so
out/target/product/onyx/system/lib/libhidlbase.so
out/target/product/onyx/system/lib/libhidlmemory.so
out/target/product/onyx/system/lib/libhidltransport.so
out/target/product/onyx/system/lib/libhwbinder.so
out/target/product/onyx/system/lib/libmedia_omx.so
out/target/product/onyx/system/lib/libmedia.so
out/target/product/onyx/system/lib/libstagefright_foundation.so
out/target/product/onyx/system/lib/libstagefright_omx.so
out/target/product/onyx/system/lib/libstagefright.so
out/target/product/onyx/system/lib/libsuspend.so
out/target/product/onyx/system/lib/libsysutils.so
out/target/product/onyx/system/lib/libui.so
out/target/product/onyx/system/lib/libutils.so
out/target/product/onyx/system/lib/libvold_binder_shared.so
out/target/product/onyx/system/lib/libwificond_ipc_shared.so
out/target/product/onyx/system/lib/netd_aidl_interface-V2-cpp.so
out/target/product/onyx/system/lib/netd_event_listener_interface-V1-cpp.so"

SYSROOT_INCLUDE_FOLDERS="frameworks/av
frameworks/native/headers/media_plugin
frameworks/native/include/gui
frameworks/native/include/media/openmax
frameworks/native/libs/binder/include
frameworks/native/libs/gui/include
frameworks/native/libs/math/include
frameworks/native/libs/nativebase/include
frameworks/native/libs/nativewindow/include
frameworks/native/libs/ui/include
frameworks/native/opengl/include
gonk-misc/libcarthage/HWC
gonk-misc/libcarthage/include
hardware/libhardware/include
hardware/libhardware_legacy/include
out/soong/.intermediates/frameworks/av/camera/libcamera_client/android_arm_armv7-a-neon_krait_core_shared/gen/aidl
out/soong/.intermediates/frameworks/av/media/libaudioclient/libaudioclient/android_arm_armv7-a-neon_krait_core_shared/gen/aidl
out/soong/.intermediates/frameworks/av/media/libmedia/libmedia_omx/android_arm_armv7-a-neon_krait_core_shared/gen/aidl
out/soong/.intermediates/system/connectivity/wificond/libwificond_ipc/android_arm_armv7-a-neon_krait_core_static/gen/aidl
out/soong/.intermediates/system/vold/libvold_binder_shared/android_arm_armv7-a-neon_krait_core_shared/gen/aidl
out/soong/.intermediates/gonk-misc/gonk-binder/binder_b2g_connectivity_interface-cpp-source/gen
out/soong/.intermediates/gonk-misc/gonk-binder/binder_b2g_telephony_interface-cpp-source/gen
out/soong/.intermediates/hardware/interfaces/gnss/1.0/android.hardware.gnss@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/gnss/1.1/android.hardware.gnss@1.1_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/gnss/2.0/android.hardware.gnss@2.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/gnss/measurement_corrections/1.0/android.hardware.gnss.measurement_corrections@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/gnss/visibility_control/1.0/android.hardware.gnss.visibility_control@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/graphics/bufferqueue/1.0/android.hardware.graphics.bufferqueue@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/graphics/bufferqueue/2.0/android.hardware.graphics.bufferqueue@2.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/graphics/common/1.0/android.hardware.graphics.common@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/graphics/common/1.1/android.hardware.graphics.common@1.1_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/graphics/common/1.2/android.hardware.graphics.common@1.2_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/media/1.0/android.hardware.media@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/media/omx/1.0/android.hardware.media.omx@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/radio/1.0/android.hardware.radio@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/sensors/1.0/android.hardware.sensors@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/vibrator/1.0/android.hardware.vibrator@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/1.0/android.hardware.wifi@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/1.1/android.hardware.wifi@1.1_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/1.2/android.hardware.wifi@1.2_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/1.3/android.hardware.wifi@1.3_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/hostapd/1.0/android.hardware.wifi.hostapd@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/hostapd/1.1/android.hardware.wifi.hostapd@1.1_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/supplicant/1.0/android.hardware.wifi.supplicant@1.0_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/supplicant/1.1/android.hardware.wifi.supplicant@1.1_genc++_headers/gen
out/soong/.intermediates/hardware/interfaces/wifi/supplicant/1.2/android.hardware.wifi.supplicant@1.2_genc++_headers/gen
out/soong/.intermediates/system/libhidl/transport/base/1.0/android.hidl.base@1.0_genc++_headers/gen
out/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager@1.0_genc++_headers/gen
out/soong/.intermediates/system/netd/resolv/dnsresolver_aidl_interface-V2-cpp-source/gen
out/soong/.intermediates/system/netd/server/netd_aidl_interface-V2-cpp-source/gen
out/soong/.intermediates/system/netd/server/netd_event_listener_interface-V1-cpp-source/gen
system/connectivity
system/core/base/include
system/core/include
system/core/libcutils/include
system/core/liblog/include
system/core/libprocessgroup/include
system/core/libsuspend/include
system/core/libsync/include
system/core/libsystem/include
system/core/libsysutils/include
system/core/libutils/include
system/libhidl/base/include
system/libhidl/transport/token/1.0/utils/include
system/media/audio/include
system/media/camera/include"

tar -c $SYSROOT_PREBUILTS $SYSROOT_LIBRARIES $SYSROOT_INCLUDE_FOLDERS --transform 's,^,b2g-sysroot/,S' | $GECKO_PATH/taskcluster/scripts/misc/zstdpy > "old-b2g-sysroot.tar.zst"
