name: auto_send_commit_to_tg
on: 
   repository_dispatch:
     types: 
       - commit
   schedule:
    - cron: '0 23 * * *'

jobs:
  commit-send:
    runs-on: ubuntu-16.04
    steps:
    - name: Check Commit
      run: |
        cd ~
        git clone https://github.com/kaiostech/gecko-b2g  -b gonk
        cd gecko-b2g
        #today
        export today=$(date +%Y-%m-%d)
        #yesterday 
        export yesterday=$(date -d "yesterday" +%Y-%m-%d)
        git log --since ==${yesterday} >> log
        cat log
        echo $yesterday
        
    - name: Send Commit
      run: |
        cd ~/gecko-b2g
        export mess=`cat log`
        export yesterday=$(date -d "yesterday" +%Y-%m-%d)
        export title="Commits date: $yesterday"
        echo $title
        if [ -s ./log ]; then
           curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=$title"
           mess=${mess//commit/|commit}
           log="$mess |commit"
           mess=${mess/|commit}
           while :
            do
              if [ ! -n "$mess" ]; then
               exit 0
              fi
              subcommit=${mess%%|*}
              curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=$subcommit"
              log=${log#*|commit}
           done
        fi
