name: auto2
on: 
#  push:
#    branches:
#      - master
#  schedule:
#    - cron: '*/5 * * * *'


env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}} 
  WEB_SERT:  ${{secrets.WEB_SERT}} 

jobs:

  Schedule:
    runs-on: ubuntu-16.04
    steps:
    - name: Initializing environment
      run: |
        echo 123
