name: auto_send_commit_to_tg
on: 
   repository_dispatch:
     types: 
       - commit
   schedule:
    - cron: '0 23 * * *'

jobs:
  commit-send:
    runs-on: ubuntu-16.04
    steps:
    - name: Check Commit
      run: |
        cd ~
        git clone https://github.com/kaiostech/gecko-b2g  -b gonk
        git clone https://github.com/kaiostech/gonk-misc -b main
        cd ~/gecko-b2g
        #today
        export today=$(date +%Y-%m-%d)
        #yesterday 
        export yesterday=$(date -d "yesterday" +%Y-%m-%d)
        git log --since=${yesterday} >> ~/log.gecko
        cd ~/gonk-misc
        git log --since=${yesterday} --until=${yesterday} >> ~/log.gonk
        echo $yesterday
        
    - name: Send Gecko Commit
      run: |
        cd ~
        export mess=`cat ~/log.gecko`
        export yesterday=$(date -d "yesterday" +%Y-%m-%d)
        export title="gecko-b2g - commits date: $yesterday"
        echo $title
        if [ -s ~/log.gecko ]; then
           curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=$title"
           mess=${mess//commit/|commit}
           mess="$mess |commit"
           mess=${mess/|commit}
           while :
            do
              if [ ! -n "$mess" ]; then
               exit 0
              fi
              subcommit=${mess%%|*}
              echo -----------------------------
              echo $subcommit
              if [[ $subcommit =~ phabricator || $subcommit =~ release+treescript@mozilla.org ]]; then 
               echo "yes";
              else 
               echo "no";
               curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=$subcommit"
              fi
              mess=${mess#*|commit}
           done
        else
         curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=commits:gecko:Null"
        fi


    - name: Send gonk Commit
      run: |
        cd ~
        export mess=`cat ~/log.gonk`
        export yesterday=$(date -d "yesterday" +%Y-%m-%d)
        export title="gonk - commits date: $yesterday"
        echo $title
        if [ -s ~/log.gonk ]; then
           curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=$title"
           mess=${mess//commit/|commit}
           mess="$mess |commit"
           mess=${mess/|commit}
           while :
            do
              if [ ! -n "$mess" ]; then
               exit 0
              fi
              subcommit=${mess%%|*}
              curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=$subcommit"
              mess=${mess#*|commit}
           done
        else
         curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=commits:gonk:Null"
        fi
