name: b2g-onyx-part6-build-gecko
on:
  schedule:
    - cron: '0 23 */3 * *'
  repository_dispatch:
    types: 
      - b2g-onyx-part6-build-gecko

env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}} 
jobs:  
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1

   
    - name: Initialization system environment
      run: |
        df -h
        sudo apt install git make mercurial  yasm  libncurses5
        wget http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.bz2
        tar xfj nasm-2.14.02.tar.bz2
        cd nasm-2.14.02/
        ./autogen.sh
        ./configure --prefix=/usr/local/ 
        make 
        sudo make install
        #hash -d nasm
        nasm -v
        cd ~
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        #curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        #cargo install sccache
        #ssh
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        #rclone
        mkdir -p ~/.config/rclone
        git clone git@github.com:ittat/tmp.git
        cd tmp
        mv ./rclone.conf ~/.config/rclone
        brew install rclone
        rclone ls itd:test
        
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo install sccache


    - name: Fetch source
      run: |
        df -h
        cd ~
        rclone copy  itd:ci/b2g_onyx/b2g-sysroot.tar.zst ./
        #rclone copy  itd:ci/b2g_onyx/old-b2g-sysroot.tar.zst ./
        curl https://packages.preprod.kaiostech.com/ndk/v2/mozbuild.tar.bz2 -o mozbuild.tar.bz2
        tar -xvf mozbuild.tar.bz2
        tar -C "$HOME/.mozbuild" -I zstd -x -a -f b2g-sysroot.tar.zst
        #mkdir -p $HOME/.mozbuild/b2g-sysroot
        #tar -C "$HOME/.mozbuild/b2g-sysroot" -I zstd -x -a -f old-b2g-sysroot.tar.zst
        sudo rm mozbuild.tar.bz2
        cd ~
        git clone https://github.com/kaiostech/gecko-b2g -b gonk
        #git clone https://github.com/ittat/gecko-b2g-1 -b gonk --depth=1
        #git clone https://github.com/OnePlus-onyx/gecko-dev -b onyx-test1
        #mv gecko-dev gecko-b2g
        #TODO
        cd gecko-b2g
        # git branch test13
        # NO f595b3d88f54d1b8d1ff243cfbd2877fe29cbeeb
        # no test 817ac2e37fd0ab19518cd4a485e419651107e597
        # no test 2ce1627bc6374b51246c78806287f4c3ad74741f
        # No a88bff5aefecbe554f06b8aa5678e09a60b714f2
        # db9b06b4817197128a16e40d736f0fdf1a65e968
        # testing 47adc72ef716a81b005df36f2ec97e291fb3caae
        # no 1e7204b819c2296763a98f7cea79a9ed03e18d59
        # no cd1819dfedc4369c1c5ef85b33d4dbe103cb37e5
        git branch test13  e9900b5419137e7334734bf9322ed687117f1aa5
        # testing 9be70dd01911b5d2d3a827645cc4df2ed953cd29
        # work 0944cec181379cef24a80a2be150451d9a1f312c
        # work f5894e94d8e2c6596a28638322ee2e82fd5c2d09
        # work 4c51fb9e9b7f95e583b4a1adfccba740b6e0132a
        # work d319abba969f78dbc27d7fdcea38bf27ce259355
        git checkout test13
        sudo rm -rf ./.repo
        df -h

    - name: check source
      run: |
        cd ~
        #sudo rm old-b2g-sysroot.tar.zst
        
        

    - name: bootstrap source
      run: |
        df -h
        cd ~/gecko-b2g
        export SHELL=/bin/bash
        export LOCAL_NDK_BASE_URL='ftp://ftp.kaiostech.com/ndk/android-ndk'
        ./mach bootstrap --no-interactive --application-choice 'GeckoView/Firefox for Android'
        df -h
        
    - name: Building X86_64
      run: |
        df -h
        cd ~/gecko-b2g
        export SHELL=/bin/bash
        export GONK_PATH=${HOME}/.mozbuild/b2g-sysroot
        #b2g_onyx??
        export GONK_PRODUCT_NAME=onyx
        export GECKO_OBJDIR=${GONK_PATH}/objdir-onyx-gecko
        export PLATFORM_VERSION=29
        export TARGET_ARCH=arm
        export TARGET_ARCH_VARIANT=armv7-a-neon
        export TARGET_CPU_VARIANT=krait
        export MOZ_DISABLE_LTO=1
        ./build-b2g.sh
        ./build-b2g.sh package
        df -h
        ls ${GECKO_OBJDIR}/dist

    - name: Send Notify
      run: |
        today=$(date +%Y-%m-%d)
        curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}}:b2g-build-gecko PASS!"



    - name: Upload 
      continue-on-error: true
      if: github.event.action == 'b2g-onyx-part6-build-gecko'
      uses: actions/upload-artifact@master
      with:
        name: b2g-81.0a1.en-US.linux-androideabi-arm.tar.gz
        path: ~/.mozbuild/b2g-sysroot/objdir-onyx-gecko/dist/b2g-81.0a1.en-US.linux-androideabi-arm.tar.gz


    - name: Upload 
      continue-on-error: true
      if: github.event.action == 'b2g-onyx-part6-build-gecko'
      uses: actions/upload-artifact@master
      with:
        name: b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz
        path: ~/.mozbuild/b2g-sysroot/objdir-onyx-gecko/dist/b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz

#     - name: update 
#       run: |
#         df -h
#         cd ~/.mozbuild/b2g-sysroot/objdir-onyx-gecko/dist
#         rclone copy ./b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz itd:ci/b2g_onyx
#         df -h
