name: b2g-android-repack-part1
on:
  repository_dispatch:
    types: 
      - b2g-repack-android-part1

env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}} 

jobs:
  Download:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1
        
    - name: Initialization system environment
      run: |
        df -h
        more /System/Library/CoreServices/SystemVersion.plist
        sudo xcode-select --switch /Applications/Xcode_10.3.app/Contents/Developer
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install expect  gnu-sed ccache
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        #mount
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 150g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        #zstd
        cd  /Volumes/android
        git clone https://github.com/facebook/zstd.git
        cd zstd
        make
        sudo make install 
        #gupload
        #curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh | sh -s
        #touch ~/.googledrive.conf
        #echo ${{secrets.GUP_CLIENT_ID}} >> ~/.googledrive.conf
        #echo ${{secrets.GUP_CLIENT_SECRET}} >> ~/.googledrive.conf
        #echo ${{secrets.GUP_ACCESS_TOKEN}} >> ~/.googledrive.conf
        #echo ${{secrets.GUP_ACCESS_TOKEN_EXPIRY}} >> ~/.googledrive.conf
        #echo ${{secrets.GUP_REFRESH_TOKEN}} >> ~/.googledrive.conf
        #echo ${{secrets.GUP_ROOT_FOLDER}} >> ~/.googledrive.conf    
        #ssh
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        #rclone
        mkdir -p ~/.config/rclone
        git clone git@github.com:ittat/tmp.git
        cd tmp
        mv ./rclone.conf ~/.config/rclone
        brew install rclone
        rclone ls itd:test
        
        
        
    - name: Fetch source
      run: |
        df -h
        export CCACHE_DIR=~/.ccache
        /usr/local/bin/ccache  -M 70G
        /usr/local/bin/ccache -s
        #export CCACHE_COMPRESS=1
        export USE_CCACHE=1
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        cd /Volumes/android
        git clone https://github.com/kaiostech/B2G -b master  --depth=1 
        cd ./B2G
        echo Download ...
        REPO_INIT_FLAGS="--depth=1" REPO_SYNC_FLAGS=" -j128 --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune" ./config.sh emulator-10-x86_64
        cd ~
        git clone https://github.com/OnePlus-onyx/build-CI -b emulator-build
        df -h

#     - name: test
#       run: |
#         # Install tmate on macOS or Ubuntu
#         echo Setting up tmate...
#         if [ -x "$(command -v brew)" ]; then
#           brew install tmate > /tmp/brew.log
#         fi
#         if [ -x "$(command -v apt-get)" ]; then
#           curl -fsSL git.io/tmate.sh | bash
#         fi
#         [ -e ~/.ssh/id_rsa ] || ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
#         echo Running tmate...
#         tmate -S /tmp/tmate.sock new-session -d
#         tmate -S /tmp/tmate.sock wait tmate-ready
#         # Print connection info
#         DISPLAY=1
#         while [ $DISPLAY -le 130 ]; do
#           echo ________________________________________________________________________________
#           echo To connect to this session copy-n-paste the following into a terminal or browser:
#           tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
#           tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
#           [ ! -f /tmp/keepalive ] && echo -e "After connecting you can run 'touch /tmp/keepalive' to disable the 30m timeout"
#           DISPLAY=$(($DISPLAY+1))
#           sleep 30
#         done
#         if [[ ! -z "$SLACK_WEBHOOK_URL" ]]; then
#           MSG=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
#           curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"\`$MSG\`\"}" $SLACK_WEBHOOK_URL
#         fi
#         # Wait for connection to close or timeout in 15 min
#         timeout=$((30*60))
#         while [ -S /tmp/tmate.sock ]; do
#           sleep 1
#           timeout=$(($timeout-1))
#           if [ ! -f /tmp/keepalive ]; then
#             if (( timeout < 0 )); then
#               echo Waiting on tmate connection timed out!
#               sudo init 0
#               exit 0
#             fi
#           fi
#         done

    - name: fix soucre
      run: |
        df -h
        cd /Volumes/android/B2G
        sed -i '' '14d'  system/sepolicy/tests/Android.bp
        cd gonk-misc
        git am ~/build-CI/0001-err.patch
        cd ../
        # Force compressing debug symbols
        cd build/soong
        git am ~/build-CI/0001-gz.patch
        cd ../../
        sudo rm -rf .repo

    - name: repack soucre
      run: |
        cd  /Volumes/android
        tar -cvf ./B2G.tar ./B2G
        zstd ./B2G.tar
        sudo rm ./B2G.tar
        sudo rm -r ./B2G
        ls -al -h ./
        df -h
        
    - name: update 
      run: |
        df -h
        cd /Volumes/android/
        #mv ./B2G.tar.zst ./B2G.tar.zst
        #~/.google-drive-upload/bin/gupload -o ./B2G.tar.zst
        rclone copy ./B2G.tar.zst itd:ci 
        df -h
        
    - name: send webhook          
      run: |
        cd /Volumes/android/
        curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "b2g-build1-part2"}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
        
        
        
