name: b2g-onyx-part5-repack-sysroot
on:
  repository_dispatch:
    types: 
      - b2g-onyx-part5-repack-sysroot
env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}} 
jobs:
  repack_sysroot:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1
     
    - name: Initialization system environment
      run: |
        df -h
        more /System/Library/CoreServices/SystemVersion.plist
        sudo xcode-select --switch /Applications/Xcode_10.3.app/Contents/Developer
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install expect  gnu-sed ccache coreutils
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        #mount
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 420g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        #zstd
        cd  /Volumes/android
        git clone https://github.com/facebook/zstd.git
        cd zstd
        make
        sudo make install 
        #ssh
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        #rclone
        mkdir -p ~/.config/rclone
        git clone git@github.com:ittat/tmp.git
        cd tmp
        mv ./rclone.conf ~/.config/rclone
        brew install rclone
        rclone ls itd:test
        
    - name: Fetch B2G source
      run: |
        df -h
        export CCACHE_DIR=~/.ccache
        /usr/local/bin/ccache  -M 70G
        /usr/local/bin/ccache -s
        export USE_CCACHE=1
        cd /Volumes/android
        rclone copy itd:ci/onyx/B2G.tar.zst ./
        zstd --decompress B2G.tar.zst
        sudo rm -r ./B2G.tar.zst
        tar -xvf ./B2G.tar ./B2G
        sudo rm -r ./B2G.tar
        ls
        df -h
        
    - name: Fetch pre-build-out source
      run: |     
        cd /Volumes/android/B2G
        rclone copy itd:ci/onyx/out3.tar.zst ./
        zstd --decompress out3.tar.zst
        sudo rm -r ./out3.tar.zst
        tar -xvf ./out3.tar ./out
        sudo rm -r ./out3.tar
        ls ./out
        df -h
        
    - name: build soucre
      run: |
        df -h
        sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
        cd /Volumes/android/B2G
        export DISABLE_SOURCES_XML=true
        ./build.sh -j4 dist DIST_DIR=dist_output
        ls -al dist_output
        df -h
 
        
    - name: repack sysroot 
      run: |
        df -h
        git clone https://github.com/OnePlus-onyx/build-CI -b b2g
        cd build-CI
        cp ./package_onyx_sysroot.sh ~/
        chmod +x ~/package_onyx_sysroot.sh
        #
        cd /Volumes/android/B2G
        cp ~/package_onyx_sysroot.sh ./
        pip3 install zstandard
        pip install zstandard
        #
        ./package_onyx_sysroot.sh
        ls -al -h b2g-sysroot.tar.zst
        ls
        df -h
        
    - name: update 
      run: |
        df -h
        cd /Volumes/android/B2G
        #~/.google-drive-upload/bin/gupload -o ./b2g-sysroot.tar.zst
        rclone copy ./b2g-sysroot.tar.zst itd:ci/onyx 
        df -h
        
    - name: Send Notify
      run: |
        today=$(date +%Y-%m-%d)
        curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}} PASS!"
 

    - name: Upload b2g_onyx-target_files-eng.runner.zip
      uses: actions/upload-artifact@master
      with:
        name: b2g_onyx-target_files-eng.runner.zip
        path: /Volumes/android/B2G/dist_output/b2g_onyx-target_files-eng.runner.zip

    - name: Upload  b2g_onyx-img-eng.runner.zip
      uses: actions/upload-artifact@master
      with:
        name: b2g_onyx-img-eng.runner.zip
        path: /Volumes/android/B2G/dist_output/b2g_onyx-img-eng.runner.zip
    
    - name: send webhook          
      run: |
        cd /Volumes/android/
        curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "b2g-onyx-part6-build-gecko"}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
        
