name: b2g-emulator-part6-build-gecko
on:
#   push:
#     branches: 
#       - master
  schedule:
    - cron: '0 23 */3 * *'
  repository_dispatch:
    types: 
      - b2g-emulator-part6-build-gecko


env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}} 
jobs:  
  build2:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1

   
    - name: Initialization system environment
      run: |
        df -h
        sudo apt install git make mercurial  yasm  libncurses5
        wget http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.bz2
        tar xfj nasm-2.14.02.tar.bz2
        cd nasm-2.14.02/
        ./autogen.sh
        ./configure --prefix=/usr/local/ 
        make 
        sudo make install
        #hash -d nasm
        nasm -v
        cd ~
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        #curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        #cargo install sccache
        #ssh
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        #rclone
        mkdir -p ~/.config/rclone
        git clone git@github.com:ittat/tmp.git
        cd tmp
        mv ./rclone.conf ~/.config/rclone
        brew install rclone
        rclone ls itd:test
        
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo install sccache


    - name: Fetch source
      run: |
        df -h
        cd ~
        #wget https://firefoxci.taskcluster-artifacts.net/SqAWos4HSqSIZjNnf_yRxQ/0/public/build/b2g-sysroot.tar.zst
        rclone copy  itd:ci/emulator/b2g-sysroot.tar.zst ./
        #curl https://packages.preprod.kaiostech.com/ndk/mozbuild.tar.bz2 -o mozbuild.tar.bz2
        curl https://packages.preprod.kaiostech.com/ndk/v2/mozbuild.tar.bz2 -o mozbuild.tar.bz2
        tar -xvf mozbuild.tar.bz2
        tar -C "$HOME/.mozbuild" -I zstd -x -a -f b2g-sysroot.tar.zst
        sudo rm b2g-sysroot.tar.zst
        sudo rm mozbuild.tar.bz2
        cd ~
        #git clone https://github.com/kaiostech/gecko-b2g -b gonk --depth=1
        git clone https://github.com/ittat/gecko-b2g-1 -b gonk --depth=1
        #cd gecko-b2g
        #git branch test1 47adc72ef716a81b005df36f2ec97e291fb3caae
        #git checkout test1
        df -h

    - name: check source
      run: |
        ls $HOME/.mozbuild/b2g-sysroot
        sudo apt install tree
        tree $HOME/.mozbuild/b2g-sysroot/include
        #ls $HOME/.mozbuild/b2g-sysroot/include/hardware_legacy
        

    - name: bootstrap source
      run: |
        df -h
        cd ~/gecko-b2g-1
        export SHELL=/bin/bash
        export LOCAL_NDK_BASE_URL='ftp://ftp.kaiostech.com/ndk/android-ndk'
        ./mach bootstrap --no-interactive --application-choice 'GeckoView/Firefox for Android'
        df -h
        
    - name: Building X86_64
      run: |
        df -h
        cd ~/gecko-b2g
        export SHELL=/bin/bash
        export GONK_PATH=${HOME}/.mozbuild/b2g-sysroot
        export GONK_PRODUCT_NAME=generic_x86_64
        export GECKO_OBJDIR=${GONK_PATH}/objdir-emulator-gecko
        export PLATFORM_VERSION=29
        export TARGET_ARCH=x86_64
        export TARGET_ARCH_VARIANT=x86_64
        export TARGET_CPU_VARIANT=generic
        export BINSUFFIX=64
        export MOZ_DISABLE_LTO=1
        ./build-b2g.sh
        ./build-b2g.sh package
        df -h
        ls ${GECKO_OBJDIR}/dist

    - name: Send Notify
      run: |
        today=$(date +%Y-%m-%d)
        curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}}:b2g-build-gecko PASS!"
        
    - name: Upload 
      if: github.event.action == 'b2g-build-gecko-part6'
      uses: actions/upload-artifact@master
      with:
        name: b2g-81.0a1.en-US.linux-android-x86_64.tar.gz
        path: ~/.mozbuild/b2g-sysroot/objdir-emulator-gecko/dist/b2g-81.0a1.en-US.linux-android-x86_64.tar.gz
