
name: Build root sys armhf

on: 
  push:
    branches:
      - test



env:
  ARCH: amd64
  version: focal

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Core Packages
      run: |
        sudo apt update && sudo apt install debootstrap neofetch -y && neofetch
        sudo apt-get install qemu-user-static -y

    # Runs a set of commands using the runners shell
    - name: Building Rootfs
      run: |
        mkdir rootfs
        wget http://cdimage.ubuntu.com/ubuntu-base/releases/18.04/release/ubuntu-base-18.04.1-base-armhf.tar.gz
        tar -xzvf   ./ubuntu-base-18.04.1-base-armhf.tar.gz -C  ./rootfs
        #sudo debootstrap --arch=$ARCH --foreign $version rootfs
        ls -l ./rootfs
        #sudo cp /usr/bin/qemu-arm-static ./rootfs/usr/bin/
        #sudo cp /usr/bin/qemu-aarch64-static ./rootfs/usr/bin/
        #sudo mount -t proc /proc ./rootfs/proc
        
      # Runs a set of commands using the runners shell
#     - name: Saving Rootfs
#       run: |
#         cd rootfs
#         sudo tar -czvf rootfs-$version-$ARCH.tar.gz *
#         mv rootfs-$version-$ARCH.tar.gz ../
#         cd ..
#     - name: Uploading Rootfs
#       run: |
#        curl -sL https://git.io/file-transfer | sh
#        ./transfer wet rootfs-$version-$ARCH.tar.gz
