#=================================================
# Description: Build ubports using GitHub Actions
# Lisence: MIT
#=================================================

name: Build Ubport 7.1
on: 
  push:
    branches:
      - ut-7.1
  schedule:
    - cron: 0 8  1 * ?
env:
  SSH_ACTIONS: false

jobs:

  build:
    runs-on: ubuntu-16.04

    env:
      DEVICE: onyx
      ANDROID_ROOT: /home/runner/work/halium/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib m4 libxml2-utils \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev repo libwxgtk3.0-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git
        sudo docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
    - name: Downloading source code
      run: |
        export DEVICE="onyx"
        export ANDROID_ROOT=/home/runner/work/halium
        export PATH=$PATH:~/bin/
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1
        repo sync -j8 -c --no-clone-bundle --no-tags
        
    - name: Clone device spec source
      run: |
        export DEVICE="onyx"
        export ANDROID_ROOT=/home/runner/work/halium
        export PATH=$PATH:~/bin/
        git clone https://github.com/OnePlus-onyx/device_oneplus_onyx.git  -b ut-7.1  $ANDROID_ROOT/device/oneplus/onyx --depth=1
        git clone https://github.com/OnePlus-onyx/android_device_oppo_common.git  -b ut-7.1   $ANDROID_ROOT/device/oppo/common --depth=1
        git clone https://github.com/OnePlus-onyx/kernel_oneplus_onyx.git  -b ut-7.1 $ANDROID_ROOT/kernel/oneplus/onyx --depth=1
        git clone https://github.com/OnePlus-onyx/proprietary_vendor_oneplus.git  -b ut-7.1  $ANDROID_ROOT/vendor/oneplus --depth=1

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Build HAL
      run: |
        export DEVICE="onyx"
        export ANDROID_ROOT=/home/runner/work/halium
        export PATH=$PATH:~/bin/
        source halium.env
        cd $ANDROID_ROOT
        # replace something
        sed -i 's/external\/selinux/external\/selinux external\/libcurl/g' build/core/main.mk
        export LC_ALL=C
        chmod +x $ANDROID_ROOT/kernel/oneplus/onyx/scripts/gcc-wrapper.py
        source build/envsetup.sh
        export USE_CCACHE=1
        breakfast $DEVICE
        make -j$(nproc) mkbootimg
        make -j$(nproc) halium-boot
        make -j$(nproc) systemimage 
        echo "md5sum halium-boot.img and system.img"
        md5sum $ANDROID_ROOT/out/target/product/onyx/halium-boot.img
        md5sum $ANDROID_ROOT/out/target/product/onyx/system.img

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: halium-boot image
        path: /home/runner/work/halium/out/target/product/onyx/halium-boot.img

    - name : Upload system image
      uses: actions/upload-artifact@master
      with:
        name: System image
        path: /home/runner/work/halium/out/target/product/onyx/system.img 
