
name: Build System Image

on: 
  push:
    branches:
      - aosp-gsi

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Clean system environment
      continue-on-error: true
      run: |
        cd ~
        hdiutil detach /Volumes/android
        rm android.dmg.sparseimage
        df -h

    - name: Initialization system environment
      run: |
        df -h
        sudo xcode-select --switch /Applications/Xcode_11.4.app/Contents/Developer
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install autoconf expect  gnu-sed ccache
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 230g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        df -h
        
    - name: Fetch source
      run: |
        df -h
        export CCACHE_DIR=~/.ccache
        /usr/local/bin/ccache  -M 50G
        export CCACHE_COMPRESS=1
        export USE_CCACHE=1
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        cd /Volumes/android
        brew install repo
        ls
        #./repo init -u git://github.com/ReB2GOS/manifests.git -b exp   --depth=1 
        repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r31
        git clone https://github.com/phhusson/treble_manifest -b android-10.0 .repo/local_manifests
        repo sync -j128 --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune
        ls
        df -h
        
    - name: fix
      run: |
        df -h
        cd /Volumes/android
        sed -i '' '65i\'$'\n\"10\.15\"\,\n' build/soong/cc/config/x86_darwin_host.go
        cat ./build/soong/cc/config/x86_darwin_host.go 
        sed -i '' '14d'  system/sepolicy/tests/Android.bp
        cat system/sepolicy/tests/Android.bp
        sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
        df -h
#
#    - name: Setup Debug Session
#      uses: csexton/debugger-action@master


    - name: Build 
      run: |
        df -h
        cd /Volumes/android/
        export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx6G" 
        source build/envsetup.sh
        lunch treble_a64_bvS-userdebug
        make -j8 systemimage
        df -h
        
#     - name: Check
#       run: |
#         df -h
#         ls -al /Volumes/android/B2G/out/target/product/onyx 

    - name: Remove android.img
      continue-on-error: true
      run: |
        cd ~
        hdiutil detach /Volumes/android
        
    - name: Remove android.img
      run: |
        cd ~
        hdiutil detach /Volumes/android
        




