
name: Build System Image

on: 
  push:
    branches:
      - mac

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch dependencies
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install autoconf
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        df -h
        sysctl -a | grep ".cpu."
        sysctl machdep.cpu
        
    - name: Fetch source
      run: |
        df -h
        pwd
        cd ~
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        git clone https://github.com/ReB2GOS/B2G -b exp
        cd ./B2G
        REPO_INIT_FLAGS="--depth=1" REPO_SYNC_FLAGS="-j128" ./config.sh emulator-10
 
        
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
      
    - name: Build
      run: |
        df -h
        cd ~
        ls
        cd ./B2G
        export LOCAL_NDK_BASE_URL='ftp://ftp.kaiostech.com/ndk/android-ndk'
        ./build.sh -j16
        




