
name: Build B2G-desktop

on: 
  push:
    branches:
      - test



env:
  ARCH: amd64
  version: focal

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Core Packages
      run: sudo apt update && sudo apt install debootstrap neofetch -y && neofetch

    # Runs a set of commands using the runners shell
    - name: Building Rootfs
      run: |
        mkdir rootfs
        wget http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04.3-base-armhf.tar.gz
        tar xvf ubuntu-base-16.04.3-base-armhf.tar.gz -C  ./rootfs
        #sudo debootstrap --arch=$ARCH --foreign $version rootfs
        ls -l rootfs
      # Runs a set of commands using the runners shell
#     - name: Saving Rootfs
#       run: |
#         cd rootfs
#         sudo tar -czvf rootfs-$version-$ARCH.tar.gz *
#         mv rootfs-$version-$ARCH.tar.gz ../
#         cd ..
#     - name: Uploading Rootfs
#       run: |
#        curl -sL https://git.io/file-transfer | sh
#        ./transfer wet rootfs-$version-$ARCH.tar.gz
