
name: Build B2G-desktop


on: 
  push:
    branches:
      - checkboot
  schedule:
     - cron: 0 8 1-30 * ?

jobs:
  build_on_mac:
    name: check boot on mac
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name : Xcode_10.app 
      uses: actions/upload-artifact@master
      with:
        name: Xcode_10.app
        path: /Applications/Xcode_10.3.app



#     - name: Initialization system environment
#       run: |
#         df -h
#         more /System/Library/CoreServices/SystemVersion.plist
#         sudo xcode-select --switch /Applications/Xcode_10.3.app/Contents/Developer
#         /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#         brew install expect  gnu-sed ccache autoconf@2.13 gnu-tar node terminal-notifier watchman 
#         brew install nasm  yasm
#         ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
#         ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
#         cd /Users/runner
#         hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 70g ~/android.dmg
#         hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
#         df -h
        
#     - name: Fetch source
#       run: |
#         df -h
#         export CCACHE_DIR=~/.ccache
#         /usr/local/bin/ccache  -M 20G
#         /usr/local/bin/ccache -s
#         #export CCACHE_COMPRESS=1
#         export USE_CCACHE=1
#         git config --global user.name "ittat"
#         git config --global user.email "ittat@github.com"
#         cd /Volumes/android
#         #git clone  https://github.com/ReB2GOS/gecko-b2g -b gonk --depth=1
#         git clone https://github.com/mozilla/gecko-dev -b master --depth=1
        
#     - name: Build B2G
#       run: |
#         df -h
#         cd /Volumes/android/gecko-dev
#         #export LOCAL_NDK_BASE_URL='https://github.com/ReB2GOS/Note/releases/download/ndk/android-ndk-0' 
#         ./mach bootstrap --no-interactive  --application-choice 'GeckoView/Firefox for Android'
#         ./mach bootstrap --no-interactive  --application-choice 'Firefox for Desktop'
#         MOZCONFIG=./mozconfig-b2g-desktop ./mach build
#         df -h
        
#     - name : B2Gdebug.app 
#       uses: actions/upload-artifact@master
#       with:
#         name: B2Gdebug.app
#         path: /Volumes/android/gecko-b2g/obj-x86_64-apple-darwin19.4.0/dist/B2GDebug.app


#   build_on_ubuntu:
#     name: check boot on ubuntu
#     runs-on: ubuntu-latest
#     timeout-minutes: 360
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1

        
#     - name: Fetch source
#       run: |
#         df -h
#         git config --global user.name "ittat"
#         git config --global user.email "ittat@github.com"
#         mkdir ~/android
#         cd ~/android
#         #git clone  https://github.com/ReB2GOS/gecko-b2g -b gonk --depth=1
#         git clone https://github.com/mozilla/gecko-dev -b master --depth=1
        
#     - name: Build B2G
#       run: |
#         df -h
#         cd ~/android/gecko-dev
#         export SHELL=/bin/bash
#         #export LOCAL_NDK_BASE_URL='ftp://ftp.kaiostech.com/ndk/android-ndk'
#         ./mach bootstrap --no-interactive  --application-choice 'GeckoView/Firefox for Android'
#         #MOZCONFIG=./mozconfig-b2g-desktop ./mach build
#         df -h
    
        
