
name: Build System Image

on: 
  push:
    branches:
      - master
#  release:
#    types: [published]
  schedule:
    - cron: 0 8  1 * ?
  watch:
    types: [started]

env:
  SSH_ACTIONS: false

jobs:

  build:
    runs-on: ubuntu-18.04

    env:
      DEVICE: emulator-10
      ANDROID_ROOT: /home/runner/work/b2g/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y  --no-install-recommends  git 
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        df -h
    - name: Downloading source code
      run: |
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        git clone https://github.com/ReB2GOS/B2G -b exp
        cd $ANDROID_ROOT/B2G
        REPO_INIT_FLAGS="--depth=1" REPO_SYNC_FLAGS="-j128" ./config.sh emulator-10
      
        
    - name: Build B2GOS
      run: |
        df -h
        
