
name: Build B2G-desktop

on: 
  push:
    branches:
      - test
  schedule:
     - cron: 0 8 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29 * ?

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Initialization system environment
      run: |
        df -h
        sudo apt install ccache

    - name: Fetch source
      run: |
        df -h
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        mkdir ~/android
        cd ~/android
        git clone  https://github.com/ReB2GOS/gecko-b2g -b test4 --depth=1
        #git clone https://github.com/mozilla/gecko-dev -b master --depth=1
        
    - name: Build B2G
      run: |
        df -h
        cd ~/android/gecko-b2g
        ./mach bootstrap --no-interactive  --application-choice 'GeckoView/Firefox for Android'
        ./mach bootstrap --no-interactive  --application-choice 'Firefox for Desktop'
        MOZCONFIG=./mozconfig-b2g-desktop ./mach build
        #and run it with ./mach run
        #tar -zcvf /Volumes/android/b2gdebug.tar.gz /Volumes/android/gecko-b2g/obj-x86_64-apple-darwin19.4.0/dist/B2GDebug.app
        df -h
        
        
