
name: Build B2G-desktop

on: 
  push:
    branches:
      - test
  schedule:
     - cron: 0 8 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29 * ?

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Initialization system environment
      run: |
        df -h
        #sudo apt install ccache
        touch /home/runner/123.txt
        
        pwd

#     - name: Upload README.md to Google Drive
#       uses: Jodebu/upload-to-drive@master
#       with:
#           target: /home/runner/123.txt
#           credentials: ${{secrets.DRIVE_CREDENTIALS}}
#           folder: ${{secrets.DRIVE_FOLDER_ID}}

    - name: Upload to Google Drive
      uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        upload-from: ./123.txt
        upload-to: 0AOiB_t6aReyRUk9PVA/

        # For those who set up Google Drive API client ID and secret themselves
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        
