
name: Build System Image

on: 
  push:
    branches:
      - mac
#  release:
#    types: [published]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Update packages
      run: |
        df -h
        top -l 1 | head -n 10 | grep PhysMem
        sysctl machdep.cpu
