
name: Build System Image

on: 
  push:
    branches:
      - mac

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Initialization system environment
      run: |
        df -h
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install autoconf expect  gnu-sed
        sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 200g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        df -h
        
    - name: Fetch source
      run: |
        df -h
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        cd /Volumes/android
        curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o repo
        chmod +x repo
        ls
        ./repo init -u git://github.com/ReB2GOS/manifests.git -b exp   --depth=1 
        ls
        ./repo sync  -j128  --no-tags --no-clone-bundle


    - name: fix
      run: |
        cd /Volumes/android
        sed -i '' '65i\'$'\n\"10\.15\"\,\n' build/soong/cc/config/x86_darwin_host.go
        cat ./build/soong/cc/config/x86_darwin_host.go 
        sed -i '' '14d'  system/sepolicy/tests/Android.bp
        cat system/sepolicy/tests/Android.bp
        df -h
#
#    - name: Setup Debug Session
#      uses: csexton/debugger-action@master


    - name: Build 
      run: |
        df -h
        cd /Volumes/android/
        source build/envsetup.sh
        lunch lemon_onyx-eng
        make -j8
        df -h
        
    - name: Check
      run: |
        df -h
        ls -al /Volumes/android/B2G/out/target/product/onyx 

    - name: Remove android.img
      run: |
        cd ~
        hdiutil detach /Volumes/android
        




