
name: Build B2G-desktop

on: 
  push:
    branches:
      - test
  schedule:
     - cron: 0 8 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29 * ?

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Initialization system environment
      run: |
        df -h
        #sudo apt install ccache
        touch /home/runner/123.txt
        cd ~
        pwd

    - name: Upload README.md to Google Drive
      uses: Jodebu/upload-to-drive@master
      with:
          target: 123.txt
          credentials: ${{secrets.DRIVE_CREDENTIALS}}
          folder: ${{secrets.DRIVE_FOLDER_ID}}
        
