
name: Build System Image

on: 
  push:
    branches:
      - lineage

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Initialization system environment
      run: |
        df -h
        sudo xcode-select --switch /Applications/Xcode_10.3.app/Contents/Developer
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install autoconf expect  gnu-sed ccache
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 200g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        df -h
        
    - name: Fetch source
      run: |
        df -h
        export CCACHE_DIR=~/.ccache
        /usr/local/bin/ccache  -M 50G
        export CCACHE_COMPRESS=1
        export USE_CCACHE=1
        git config --global user.name "ittat"
        git config --global user.email "ittat@github.com"
        cd /Volumes/android
        curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o repo
        chmod +x repo
        ls
        git clone https://github.com/YumeMichi/android
        cp android/onyx/lineage-17.1-sultan/local_manifest.xml ./
        sudo rm -rf android
        repo init -u https://github.com/LineageOS/android.git -b lineage-17.1 --depth=1
        mv ./local_manifest.xml android/.repo/local_manifests
        cd android
        ls
        ./repo sync  -j128 --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune
        
#     - name: fix
#       run: |
#         cd /Volumes/android
#         sed -i '' '65i\'$'\n\"10\.15\"\,\n' build/soong/cc/config/x86_darwin_host.go
#         cat ./build/soong/cc/config/x86_darwin_host.go 
#         sed -i '' '14d'  system/sepolicy/tests/Android.bp
#         cat system/sepolicy/tests/Android.bp
#         sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
#         df -h
#
#    - name: Setup Debug Session
#      uses: csexton/debugger-action@master


    - name: Build 
      run: |
        df -h
        cd /Volumes/android/
        export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx6G" 
        source build/envsetup.sh
        lunch
        #lunch lemon_onyx-eng 
        #make -j8
        df -h
        
#     - name: Check
#       run: |
#         df -h
#         ls -al /Volumes/android/B2G/out/target/product/onyx 
    - name: Remove android.img
      run: |
        cd ~
        hdiutil detach /Volumes/android
        




