name: flow_run
on:
  workflow_run:
    workflows: ["auto2"]
    types:
      - completed


env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}} 
  WEB_SERT:  ${{secrets.WEB_SERT}} 

jobs:

  Schedule:
    runs-on: ubuntu-16.04
    steps:
    - name: Initializing environment
      run: |
        echo 123
