name: line-onyx-part2-build1
on:
#   push:
#     branches: 
#       - master
  repository_dispatch:
    types: 
      - line-onyx-part2-build1
env:
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}         

jobs:
  emulator_build1:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v1

        
    - name: Initialization system environment
      run: |
        df -h
        more /System/Library/CoreServices/SystemVersion.plist
        sudo xcode-select --switch /Applications/Xcode_10.3.app/Contents/Developer
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install expect  gnu-sed ccache coreutils
        ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        ln -s /usr/local/bin/g++-9 /usr/local/bin/g++
        #mount
        cd /Users/runner
        hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 210g ~/android.dmg
        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
        #zstd
        cd  /Volumes/android
        git clone https://github.com/facebook/zstd.git
        cd zstd
        make
        sudo make install 
        #ssh
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        #rclone
        mkdir -p ~/.config/rclone
        git clone git@github.com:ittat/tmp.git
        cd tmp
        mv ./rclone.conf ~/.config/rclone
        brew install rclone
        rclone ls itd:test
        
    - name: Fetch source
      run: |
        df -h
        export CCACHE_DIR=~/.ccache
        /usr/local/bin/ccache  -M 70G
        /usr/local/bin/ccache -s
        export USE_CCACHE=1
        cd /Volumes/android
        rclone copy itd:ci/lineos/B2G.tar.zst ./
        zstd --decompress B2G.tar.zst
        tar -xvf ./B2G.tar ./B2G
        sudo rm -r ./B2G.tar.zst
        sudo rm -r ./B2G.tar
        ls
        df -h
        
    - name: Fetch source
      run: |
        cd /Volumes/android/B2G
        rclone copy itd:ci/onyx/out.tar.zst ./
        zstd --decompress out.tar.zst
        sudo rm -r ./out.tar.zst
        tar -xvf ./out.tar ./out
        sudo rm -r ./out.tar
        ls ./out
        df -h
        
    - name: fix soucre
      run: |
        cd /Volumes/android/B2G/oneplus
        sudo rm -rf ./onyx
        git clone https://github.com/YumeMichi/kernel_oneplus_onyx -b dev2 --depth=1
        mv kernel_oneplus_onyx onyx
        
    - name: build soucre
      continue-on-error: true
      run: |
        df -h
        sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
        cd /Volumes/android/B2G
        export DISABLE_SOURCES_XML=true
        gtimeout 275m ./build.sh -j4
        df -h
        
    - name: repack update 
      run: |
        cd /Volumes/android/B2G
        tar -cvf ./out.tar ./out
        zstd ./out.tar
        sudo rm ./out.tar
        sudo rm -r ./out
        df -h
        
    - name: update 
      run: |
        cd /Volumes/android/B2G
        #~/.google-drive-upload/bin/gupload -o ./out.tar.zst
        rclone copy ./out.tar.zst itd:ci/lineos 
    - name: Send Notify
      run: |
        curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}} Done!"
     

#     - name: send webhook          
#       run: |
#         cd /Volumes/android/
#         curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "b2g-emulator-part3-build2"}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
        
